# Import Source Code and Enter URL

Enter direct URL from CompetitionSuite for the program to read the score tables. There may be more than one table on each page, and the below comments will help with selecting the correct parameters.

In [48]:
from src.web_scraper import scores_and_ranks

url = 'https://recaps.competitionsuite.com/b57486a9-3360-4811-87af-82dee1b030d4.htm'

## Write file name in this format [yyyy-class-show] e.g. '2023-piw-finals'
filename = '2023-piw-finals.csv'


dfs = scores_and_ranks(url)

In [49]:
## How many recaps are on the page? If there is more than one, you will need to select one in the next cell.

## View the tables
for i, df in enumerate(dfs, start=1):
    print(f"\nTABLE {i}")
    print(df.head())

print(f"There are a total of {i} tables.")

TABLE 1
              group         location  score_1  rank_1  score_2  rank_2  \
0                                         NaN     NaN      NaN     NaN
1        J. Kennedy      R. Ulibarri      NaN     NaN      NaN     NaN
2               Ovr              Mus      NaN     NaN      NaN     NaN
3  Pulse Percussion  Westminster, CA     98.5     3.0     98.5     3.0
4               RCC    Riverside, CA     99.5     2.0     98.0     4.0

   score_3  rank_3  score_4  rank_4  ...  score_27  rank_27  score_28  \
0      NaN     NaN      NaN     NaN  ...       NaN      NaN       NaN
1      NaN     NaN      NaN     NaN  ...       NaN      NaN       NaN
2      NaN     NaN      NaN     NaN  ...       NaN      NaN       NaN
3   29.550     3.0     98.0     2.0  ...     19.75      2.0    19.725
4   29.625     2.0     99.5     1.0  ...     19.80      1.0    19.900

   rank_28  score_29  rank_29  score_30  rank_30  score_31  rank_31
0      NaN       NaN      NaN       NaN      NaN       NaN      NaN
1      NaN       NaN      NaN       NaN      NaN       NaN      NaN
2      NaN       NaN      NaN       NaN      NaN       NaN      NaN
3      2.0    98.513      1.0       0.0      NaN    98.513      1.0
4      1.0    98.475      2.0       0.0      NaN    98.475      2.0

[5 rows x 64 columns]
There are a total of 1 tables.

# Preview the Table

In [52]:
which_table = 1                                   ## Select the desired table

df=dfs[which_table-1]    

df_clean=df.dropna(axis=1, how='all')             ## This will remove the unused column after penalty (all nulls)
df_clean=df_clean.dropna(axis=0, how='any')       ## This will remove the first three rows with the blanks and judge name
df_clean

,group,location,score_1,rank_1,score_2,rank_2,score_3,rank_3,score_4,rank_4,...,rank_26,score_27,rank_27,score_28,rank_28,score_29,rank_29,score_30,score_31,rank_31
3,Pulse Percussion,"Westminster, CA",98.5,3.0,98.5,3.0,29.550,3.0,98.0,2.0,...,1.0,19.75,2.0,19.725,2.0,98.513,1.0,0.00,98.513,1.0
4,RCC,"Riverside, CA",99.5,2.0,98.0,4.0,29.625,2.0,99.5,1.0,...,2.0,19.80,1.0,19.900,1.0,98.475,2.0,0.00,98.475,2.0
5,Rhythm X,"Dayton, OH",100.0,1.0,99.5,1.0,29.925,1.0,97.0,3.0,...,4.0,19.55,3.0,19.450,3.0,97.088,3.0,0.00,97.088,3.0
6,Broken City,"Lake Elsinore, CA",95.5,8.0,97.0,5.0,28.875,6.0,95.5,5.0,...,3.0,19.50,4.0,19.450,3.0,95.625,4.0,0.00,95.625,4.0
7,Infinity,"Orlando, FL",97.5,4.0,99.0,2.0,29.475,4.0,94.5,6.0,...,5.0,19.15,5.0,18.875,6.0,95.575,5.0,0.00,95.575,5.0
8,Music City Mystique,"Nashville, TN",96.5,6.0,95.0,8.0,28.725,8.0,96.5,4.0,...,6.0,19.00,7.0,19.225,5.0,94.813,6.0,0.00,94.813,6.0
9,United Percussion,"Camden County, NJ",97.0,5.0,96.5,6.0,29.025,5.0,92.0,8.0,...,8.0,18.90,8.0,18.400,9.0,94.163,7.0,0.00,94.163,7.0
10,Monarch Independent,"Houston, TX",96.0,7.0,96.0,7.0,28.800,7.0,91.0,9.0,...,10.0,18.10,10.0,18.025,12.0,93.000,9.0,0.00,93.000,8.0
11,Matrix,"Akron, OH",94.5,10.0,93.0,11.0,28.125,11.0,94.0,7.0,...,7.0,19.10,6.0,18.700,7.0,93.225,8.0,0.35,92.875,9.0
12,George Mason University,"Fairfax, VA",95.0,9.0,94.0,10.0,28.350,9.0,90.0,10.0,...,11.0,17.85,11.0,18.050,11.0,91.450,10.0,0.00,91.450,10.0
13,POW Percussion,"Garden Grove, CA",93.0,13.0,92.5,12.0,27.825,13.0,88.0,12.0,...,13.0,17.80,12.0,18.075,10.0,90.350,12.0,0.00,90.350,11.0
14,Atlanta Quest,"Atlanta, GA",94.0,11.0,92.0,13.0,27.900,12.0,87.0,13.0,...,12.0,17.75,13.0,17.875,13.0,90.250,13.0,0.00,90.250,12.0
15,ConneXus,"Cincinnati, OH",93.5,12.0,94.5,9.0,28.200,10.0,89.0,11.0,...,9.0,18.40,9.0,18.525,8.0,90.400,11.0,1.00,89.400,13.0
16,Cap City Percussion,"Columbus, OH",89.0,15.0,88.0,15.0,26.550,15.0,86.0,14.0,...,14.0,17.20,15.0,17.200,15.0,87.675,15.0,0.00,87.675,14.0
17,Vigilantes Indoor Percussion,"Fort Worth, TX",91.0,14.0,89.0,14.0,27.000,14.0,84.0,15.0,...,15.0,17.30,14.0,17.300,14.0,88.125,14.0,7.20,80.925,15.0

# Rename Columns

Rename columns based on double panel, marching, or concert.

In [53]:

## Double Panel Marching
df_clean.columns = [
    ## GROUP INFO
    'group', 'location', 
    
    ## EFFECT - MUSIC
    'eff-mus-ovr-score-a', 'eff-mus-ovr-rank-a', 'eff-mus-mus-score-a', 'eff-mus-mus-rank-a', 'eff-mus-tot-score-a', 'eff-mus-tot-rank-a', ## JUDGE 1
    'eff-mus-ovr-score-b', 'eff-mus-ovr-rank-b', 'eff-mus-mus-score-b', 'eff-mus-mus-rank-b', 'eff-mus-tot-score-b', 'eff-mus-tot-rank-b', ## JUDGE 2
    'eff-mus-tot-score', 'eff-mus-tot-rank', ## OVERALL
    
    ## EFFECT - VISUAL
    'eff-vis-ovr-score-a', 'eff-vis-ovr-rank-a', 'eff-vis-mus-score-a', 'eff-vis-mus-rank-a', 'eff-vis-tot-score-a', 'eff-vis-tot-rank-a', ## JUDGE 1
    'eff-vis-ovr-score-b', 'eff-vis-ovr-rank-b', 'eff-vis-mus-score-b', 'eff-vis-mus-rank-b', 'eff-vis-tot-score-b', 'eff-vis-tot-rank-b', ## JUDGE 2
    'eff-vis-tot-score', 'eff-vis-tot-rank', ## OVERALL

    ## MUSIC
    'mus-comp-score-a', 'mus-comp-rank-a', 'mus-perf-score-a', 'mus-perf-rank-a', 'mus-tot-score-a', 'mus-tot-rank-a', ## JUDGE 1
    'mus-comp-score-b', 'mus-comp-rank-b', 'mus-perf-score-b', 'mus-perf-rank-b', 'mus-tot-score-b', 'mus-tot-rank-b', ## JUDGE 2
    'mus-tot-score', 'mus-tot-rank', ## OVERALL

    ## VISUAL
    'vis-comp-score-a', 'vis-comp-rank-a', 'vis-perf-score-a', 'vis-perf-rank-a', 'vis-tot-score-a', 'vis-tot-rank-a', ## JUDGE 1
    'vis-comp-score-b', 'vis-comp-rank-b', 'vis-perf-score-b', 'vis-perf-rank-b', 'vis-tot-score-b', 'vis-tot-rank-b', ## JUDGE 2
    'vis-tot-score', 'vis-tot-rank', ## OVERALL

    ## TIMING & PENALTIES
    'subtotal-score', 'subtotal-rank', 'penalty', 'total-score', 'total-rank'
    
    ]

df_clean

,group,location,eff-mus-ovr-score-a,eff-mus-ovr-rank-a,eff-mus-mus-score-a,eff-mus-mus-rank-a,eff-mus-tot-score-a,eff-mus-tot-rank-a,eff-mus-ovr-score-b,eff-mus-ovr-rank-b,...,vis-perf-rank-b,vis-tot-score-b,vis-tot-rank-b,vis-tot-score,vis-tot-rank,subtotal-score,subtotal-rank,penalty,total-score,total-rank
3,Pulse Percussion,"Westminster, CA",98.5,3.0,98.5,3.0,29.550,3.0,98.0,2.0,...,1.0,19.75,2.0,19.725,2.0,98.513,1.0,0.00,98.513,1.0
4,RCC,"Riverside, CA",99.5,2.0,98.0,4.0,29.625,2.0,99.5,1.0,...,2.0,19.80,1.0,19.900,1.0,98.475,2.0,0.00,98.475,2.0
5,Rhythm X,"Dayton, OH",100.0,1.0,99.5,1.0,29.925,1.0,97.0,3.0,...,4.0,19.55,3.0,19.450,3.0,97.088,3.0,0.00,97.088,3.0
6,Broken City,"Lake Elsinore, CA",95.5,8.0,97.0,5.0,28.875,6.0,95.5,5.0,...,3.0,19.50,4.0,19.450,3.0,95.625,4.0,0.00,95.625,4.0
7,Infinity,"Orlando, FL",97.5,4.0,99.0,2.0,29.475,4.0,94.5,6.0,...,5.0,19.15,5.0,18.875,6.0,95.575,5.0,0.00,95.575,5.0
8,Music City Mystique,"Nashville, TN",96.5,6.0,95.0,8.0,28.725,8.0,96.5,4.0,...,6.0,19.00,7.0,19.225,5.0,94.813,6.0,0.00,94.813,6.0
9,United Percussion,"Camden County, NJ",97.0,5.0,96.5,6.0,29.025,5.0,92.0,8.0,...,8.0,18.90,8.0,18.400,9.0,94.163,7.0,0.00,94.163,7.0
10,Monarch Independent,"Houston, TX",96.0,7.0,96.0,7.0,28.800,7.0,91.0,9.0,...,10.0,18.10,10.0,18.025,12.0,93.000,9.0,0.00,93.000,8.0
11,Matrix,"Akron, OH",94.5,10.0,93.0,11.0,28.125,11.0,94.0,7.0,...,7.0,19.10,6.0,18.700,7.0,93.225,8.0,0.35,92.875,9.0
12,George Mason University,"Fairfax, VA",95.0,9.0,94.0,10.0,28.350,9.0,90.0,10.0,...,11.0,17.85,11.0,18.050,11.0,91.450,10.0,0.00,91.450,10.0
13,POW Percussion,"Garden Grove, CA",93.0,13.0,92.5,12.0,27.825,13.0,88.0,12.0,...,13.0,17.80,12.0,18.075,10.0,90.350,12.0,0.00,90.350,11.0
14,Atlanta Quest,"Atlanta, GA",94.0,11.0,92.0,13.0,27.900,12.0,87.0,13.0,...,12.0,17.75,13.0,17.875,13.0,90.250,13.0,0.00,90.250,12.0
15,ConneXus,"Cincinnati, OH",93.5,12.0,94.5,9.0,28.200,10.0,89.0,11.0,...,9.0,18.40,9.0,18.525,8.0,90.400,11.0,1.00,89.400,13.0
16,Cap City Percussion,"Columbus, OH",89.0,15.0,88.0,15.0,26.550,15.0,86.0,14.0,...,14.0,17.20,15.0,17.200,15.0,87.675,15.0,0.00,87.675,14.0
17,Vigilantes Indoor Percussion,"Fort Worth, TX",91.0,14.0,89.0,14.0,27.000,14.0,84.0,15.0,...,15.0,17.30,14.0,17.300,14.0,88.125,14.0,7.20,80.925,15.0

In [54]:

df_clean.to_csv(f"files/{filename}", index=False)